- name: install and run nginx
  hosts: web
  become: yes #become root. -b
  tasks:
  - name: install ngnix
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start ngnix
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes