- name: playbook
  hosts: local
  connection: local
  vars:
    course: "devops AWS"
    duration: 120hrs
    trainer: sivakumar
  tasks:
  - name: play1 and task1
    vars:
      course: ansible
    ansible.builtin.debug:
      msg: "course: {{ course }}; duration:{{ duration }};trainer: {{ trainer }}"