- name: playbook1
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: task1
    ansible.builtin.debug:
      msg: "course: {{ course }}; duration:{{ duration }};trainer: {{ trainer }}"