- name: play1
  hosts: local
  connection: local # managoing it's own node, no need of credentials.
  vars:
    greet: play
  vars_files:
  - course.yaml
  # vars_prompt:
  # - name: greet
  #   prompt: enter the value for greet
    # private: false
  tasks:
  - name: play1 and task1
    # vars:
    #   greet: task
    ansible.builtin.debug:
      msg: "Hello from {{ greet }}"
