- name: play1
  hosts: local
  connection: local # managoing it's own node, no need of credentials.
  vars:
    my_number: 15
  tasks:
   - name: print if number greater than 10
     ansible.builtin.debug:
        msg: " Given number {{ my_number }} is greater than 10"
      when: my_number > 10
    
    - name: print if number greater than 10
      ansible.builtin.debug:
        msg: " Given number {{ my_number }} is greater than 10"
      when: my_number <= 10