- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_distribution == "RedHat" # to access ansible facts we need to use ansible_<name of the fact that you want to use here>

- name: install nginx for ubuntu family
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_distribution == "Ubuntu"  


