- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages task
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state}}"
    loop:
    - { name: mysql ,state: present}
    - { name: gcc, state: absent }
    - { name: git , state: present }
    - { name: zip, state: present }
