- name: filters.
  hosts: local
  connection: local
  tasks:
  - name: handling undefined vairalbes.
    ansible.builtin.debug:
      msg: "{{ person | default ('bhavya' )}}"

- name: string to list
  ansible.builtin.debug:
  vars:
    fruits: "apple, banaa, orange"
  
    msg: "fruits are: {{ fruits }}"
