- name: filters.
  hosts: local
  connection: local
  tasks:
  - name: handling undefined vairalbes.
    ansible.builtin.debug:
      msg: "{{ person | default ('bhavya' )}}"

  - name: string to list
    vars:
      fruits: "apple, banaa, orange"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split (' , ')}}"

  - name: map to list
    vars:
      course: 
        name: devops
        duration:  120hrs
        trainer: siva"
    ansible.builtin.debug:
      msg: "course info is : {{ course | dict2items }}"

      
  - name: convert list to map
    vars:
      course: 
        - {'key': 'name', 'value': 'devops'}
        - {'key': 'duration', 'value': '120hrs'}
        - {'key': 'trainer', 'value': 'siva'}

    ansible.builtin.debug:
      msg: "course info is : {{ course | items2dict }}"