- name: filters.
  hosts: local
  connection: local
  tasks:
  - name: handling undefined vairalbes.
    ansible.builtin.debug:
      msg: "{{ person | default ('bhavya' )}}"

- name: string to list
  vars:
    fruits: "apple,banaa,orange"
  ansible.builtin.debug:
    msg: "{{ fruits }}"
