- name: filters.
  hosts: local
  connection: local
  tasks:
  - name: handling undefined vairalbes.
    ansible.builtin.debug:
      msg: "{{ person | default ('bhavya' )}}"

  - name: string to list
    vars:
      fruits: "apple, banaa, orange"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split (' , ')}}"

  - name: list to map
    vars:
      course: 
        name: devops
        duration:  120hrs
        trainer: siva"
    ansible.builtin.debug:
      msg: "course info is : {{ course | dict2items }}"