- name: using command and shell modes
  hosts: local
  connection: local
  tasks:
  - name: list of files.
    ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
