- name: using command and shell modes
  hosts: local
  connection: local
  tasks:
  - name: list of files
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr 
    register: command_results
  - name: print the results
    ansible.builtin.debug:
      msg: " {{ command_reuslts }} "
