- name: create ec2 and configure route 53 record
  hosts: local
  connection: local
  vars:
   subnet_id: subnet-0ad95c9d354678e08
   sg_id: sg-000c425d27de83849
   ami_id: ami-09c813fb71547fc4f
   instance_type: t3.micro
   zone: devdom.fun
   instances:
   - mysql
   - backend
   - frontend
  tasks:
  - name: install AWS python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}" 
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
    loop: "{{ instances }}"
    register: ec2_info

  # - name: print ec2 info
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_info }}"

  - name: print private ip address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"
  
  - name: create route 53 record
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      tt1: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: " {{ ec2_info.results }}"

